Add support to WiFiScanResults
edgehog-device-manager/edgehog-device-runtime pull request #123
Opened 2022-08-11 14:34 UTC by FrancescoVaiani

Add the Wi-Fi scan functionality using `iw` on Linux via the
`wifiscanner` rust crate.

Close #24 

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-09-07 14:38 UTC, harlem88 requested changes

2022-09-07 14:38 UTC, harlem88 commented on src/telemetry/wifi_scan.rs
> +fn get_struct_from_wifi(wifi: Wifi) -> Result<WifiScanResult, DeviceManagerError> {
Use `From trait` for converting the `wifi` type.
``` rust
impl TryFrom<Wifi> for WifiScanResult {
type Error = DeviceManagerError;
    fn try_from(value: AstarteType) -> Result<Self, Self::Error> {
    ....
    }
 }
 ```   
 `get_struct_from_wifi(wifi)?; -> wifi.try_into();`

2022-09-19 14:37 UTC, rbino approved these changes

2022-09-20 11:14 UTC, bettio approved these changes

2022-09-20 11:14 UTC, merged