Implement io.edgehog.devicemanager.BatteryStatus
edgehog-device-manager/edgehog-device-runtime pull request #130
Opened 2022-09-02 07:43 UTC by FrancescoVaiani

Add support to `io.edgehog.devicemanager.BatteryStatus` interface
with data from UPower collected via D-Bus.

Close #16 

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-09-22 14:20 UTC, rbino requested changes

2022-09-22 14:20 UTC, rbino commented on src/lib.rs
> +                send_telemetry(Box::new(&publisher), msg).await;
There's no need to allocate on the heap to pass the publisher reference:
- Move `send_telemetry` _inside_ the `DeviceManager` struct so you can use `T` and change its signature to:
```rust
    async fn send_telemetry(publisher: &T, msg: TelemetryMessage)
```
- At the callsite:
```rust
    Self::send_telemetry(&publisher, msg).await;
```

2022-09-26 12:59 UTC, rbino requested changes

2022-09-26 12:59 UTC, rbino commented on src/telemetry/battery_status.rs
> +    Ok(result)
I thought of another approach for this that could reduce repetition without introducing back highly indented code: As you could have a `get_powet_devices() -> Result<Something>` function that chains the calls starting from `zbus::Connection::system` with the `?` operator and then the outer function just handles the `Ok/Err` case in a single place and either iterates on `power_devices` or returns an empty HashMap

2022-09-27 10:24 UTC, harlem88 approved these changes

2022-09-27 12:35 UTC, rbino approved these changes

2022-10-03 13:41 UTC, bettio approved these changes

2022-10-03 13:41 UTC, merged