Add support to `CellularConnectionProperties`
edgehog-device-manager/edgehog-device-runtime pull request #136
Opened 2022-09-14 14:01 UTC by FrancescoVaiani

- Implement the Cellular Properties D-Bus demo service
- Add support to the `Modems` D-Bus service to retrieve the data for `io.edgehog.devicemanager.CellularConnectionProperties`

2022-09-26 13:00 UTC, rbino requested changes

2022-09-26 13:00 UTC, rbino commented on src/telemetry/cellular_modem.rs
> +    }
As in the other PR, let's try to keep (at least in new code) an early return approach vs the heavily nested approach here

2022-09-26 13:00 UTC, rbino commented on src/telemetry/cellular_modem.rs
> +    }
As in the other PR, you could have a `get_available_modems() -> Result<Something>` function that chains the calls starting from `zbus::Connection::session` with the `?` operator and then the outer function just handles the `Ok/Err` case in a single place and either iterates on `available_modems` or returns an empty HashMap

2022-09-27 12:51 UTC, rbino approved these changes

2024-09-30 14:56 UTC, joshuachp commented
Superseded by https://github.com/edgehog-device-manager/edgehog-device-runtime/pull/402

2024-09-30 14:56 UTC, closed without merging