refactor(workspace): convert the project in a workspace
edgehog-device-manager/edgehog-device-runtime pull request #230
Opened 2023-05-03 12:51 UTC by joshuachp

2023-05-03 12:53 UTC, joshuachp commented
Still a draft, I want to see if the CI whould run correctly

2023-08-08 07:36 UTC, harlem88 requested changes

2023-08-08 07:36 UTC, harlem88 commented on .cargo/config.toml
> +# This file is part of Hedgehog.
```suggestion
# This file is part of Edgehog.
```

2023-08-08 07:36 UTC, harlem88 commented on CHANGELOG.md
> +## 0.7.2 - Unreleased
```suggestion
## [Unreleased]
```

2023-08-08 07:36 UTC, harlem88 commented on Cargo.toml
>  [dependencies]
Specifying a workspace dependency to be inherited by members of a workspace.
```suggestion
[workspace.dependencies]
```

2023-08-08 07:36 UTC, harlem88 commented on e2e-test/Cargo.toml
> +astarte-device-sdk = { version = "0.5.1", features = ["derive"] }
```suggestion
astarte-device-sdk = { workspace = true, features = ["derive"] }
```

2023-08-10 12:47 UTC, harlem88 requested changes

2023-08-10 12:47 UTC, harlem88 commented on CHANGELOG.md
> +
```suggestion

```

2023-09-15 07:27 UTC, harlem88 approved these changes

2023-09-15 07:27 UTC, merged