Add OTA update
edgehog-device-manager/edgehog-device-runtime pull request #25
Opened 2022-03-09 17:10 UTC by shikoku1

2022-03-11 15:58 UTC, harlem88 commented on src/updatemanager.rs
> +pub struct UpdateManager<'a> {
@bettio What do you think about this name? IMHO it should be called something like `OTAHandler`

2022-03-15 09:16 UTC, harlem88 requested changes

2022-03-15 09:16 UTC, harlem88 commented on src/error.rs
>      #[error("urrecoverable error")]
Change this to `unrecoverable`

2022-03-16 09:42 UTC, FrancescoVaiani approved these changes

2022-03-17 17:44 UTC, harlem88 requested changes

2022-03-17 18:20 UTC, harlem88 requested changes

2022-03-17 18:20 UTC, harlem88 commented on src/updatemanager.rs
> +/*
Chage updatemanager.rs in `ota_handler.rs`

2022-03-17 18:20 UTC, harlem88 commented on src/updatemanager.rs
> +pub struct UpdateManager<'a> {
Change UpdateManager in `OTAHandler`

2022-03-18 09:09 UTC, harlem88 requested changes

2022-03-18 09:09 UTC, harlem88 commented on src/lib.rs
> +        let mut updmanager = ota_handler::OTAHandler::new(&opts).await?;
Change the local variable name to `ota_handler`

2022-03-18 09:09 UTC, harlem88 commented on src/ota_handler.rs
> +    pub async fn update_event(
Change this to `ota_event`

2022-03-18 09:09 UTC, harlem88 commented on src/ota_handler.rs
> +    async fn handle_update_event(
Change this to `handle_ota_event`

2022-03-18 14:30 UTC, harlem88 approved these changes

2022-03-21 14:45 UTC, harlem88 requested changes

2022-03-21 14:45 UTC, harlem88 commented on src/ota_handler.rs
> +enum OtaStatus {
Change this to`OTAStatus`

2022-03-21 14:45 UTC, harlem88 commented on src/ota_handler.rs
> +    pub async fn check_pending_otaresponse(
Change this to `check_pending_ota_response`

2022-03-21 14:45 UTC, harlem88 commented on src/ota_handler.rs
> +    fn map_otastatus(status: OtaStatus) -> (String, String) {
Change this to `map_ota_status`

2022-03-21 14:45 UTC, harlem88 commented on src/ota_handler.rs
> +    fn otastatus() {
Change this to `ota_status`

2022-03-21 15:11 UTC, harlem88 requested changes

2022-03-21 15:11 UTC, harlem88 commented on src/error.rs
> +    OtaError(#[from] crate::ota_handler::OTAError),
Change also this to `OTAError`

2022-03-21 15:24 UTC, harlem88 approved these changes

2022-03-21 17:39 UTC, Annopaolo requested changes

2022-03-21 17:39 UTC, Annopaolo commented on src/ota_handler.rs
> +    pub async fn check_pending_ota_response(
`check_pending_ota_response` is a bit unclear on side effects. Maybe `ensure_pending_ota_response()?

2022-03-21 17:39 UTC, Annopaolo commented on src/ota_handler.rs
> +    fn map_ota_status(status: OTAStatus) -> (String, String) {
`map` is too generic, maybe a better name can be used also here

2022-03-23 11:35 UTC, bettio requested changes

2022-03-23 11:35 UTC, bettio commented on src/main.rs
> +        interface_json_path: "/tmp/interfaces".to_string(),
revert previous line.

2022-03-23 11:35 UTC, bettio commented on src/main.rs
> +        state_file_path: "/data/dm-update".to_string(),
let's add: TODO: change following paths

2022-03-23 12:03 UTC, bettio approved these changes

2022-03-23 12:06 UTC, bettio approved these changes

2022-03-23 12:29 UTC, merged