tests: reduce the test time from >30s to <1s
edgehog-device-manager/edgehog-device-runtime pull request #252
Opened 2023-07-24 15:59 UTC by joshuachp

Remove the delays and sleep in the tests, optimize the channels into a stream. Fix flaky tests when run locally, use temp dir for ota.bin. Use tokio process and uitls to not block the main thread.

Advance time manually during tests.

2023-07-25 13:15 UTC, rgallor approved these changes

2023-07-25 13:16 UTC, rgallor approved these changes

2023-07-25 15:26 UTC, harlem88 requested changes

2023-07-25 15:26 UTC, harlem88 commented on src/ota/ota_handle.rs
> +            tokio::time::sleep(std::time::Duration::from_secs(5)).await;
`cfg!`, unlike `#[cfg]`, does not remove any code and only evaluates to true or false. [std::cfg](https://doc.rust-lang.org/std/macro.cfg.html)
Keep the version with `#[cfg]`
``` Rust
#[cfg(not(test))]{
   tokio::time::sleep(std::time::Duration::from_secs(5)).await;
   if let Err(error) = crate::power_management::reboot() {
...
}

2023-07-26 14:32 UTC, harlem88 approved these changes

2023-08-04 10:04 UTC, sorru94 approved these changes

2023-08-04 10:06 UTC, merged