feat(ota): improve tests and make the progress a stream
edgehog-device-manager/edgehog-device-runtime pull request #255
Opened 2023-07-26 12:46 UTC by joshuachp

Remove the delays and channels from the tests. Replace the test that require to receive a channel as "expect" and make it return a progress stream directly.

2023-09-25 14:22 UTC, harlem88 requested changes

2023-09-25 14:22 UTC, harlem88 commented on src/ota/ota_handler.rs
> +                return Err(DeviceManagerError::OtaError(OtaError::Request(
Here can use `let-else`
```suggestion
        let Some(AstarteType::String(operation_str)) = data.get("operation") else{
                error!("missing ota operation: {:?}", data);
                return Err(DeviceManagerError::OtaError(OtaError::Request(
```

2023-09-25 14:22 UTC, harlem88 commented on src/ota/ota_handler.rs
> +                error!("update data missing uuid: {:?}", data);
same above
```suggestion
        let Some(AstarteType::String(operation_str) = data.get("uuid") else {
                error!("update data missing uuid: {:?}", data);
                return Ok(());
          }
```

2023-09-25 14:22 UTC, harlem88 commented on src/ota/ota_handler.rs
> +        let request_uuid_str = match &data.get("uuid") {
same above use `let-else`

2023-09-28 10:35 UTC, joshuachp commented on src/ota/ota_handler.rs
> +                return Err(DeviceManagerError::OtaError(OtaError::Request(
Done

2023-09-28 10:35 UTC, joshuachp commented on src/ota/ota_handler.rs
> +                error!("update data missing uuid: {:?}", data);
Done

2023-09-28 10:35 UTC, joshuachp commented on src/ota/ota_handler.rs
> +        let request_uuid_str = match &data.get("uuid") {
Done

2023-10-09 15:21 UTC, rgallor requested changes

2023-10-13 10:29 UTC, joshuachp commented on src/ota/ota_handle.rs
>          info!("Rebooting in 5 seconds");
Yes, but misleading. I will change it

2023-10-13 13:37 UTC, harlem88 approved these changes

2023-10-27 15:49 UTC, rgallor approved these changes

2023-10-27 16:04 UTC, merged