feat(MSRV): update to rust 1.66.1 and fix some warning
edgehog-device-manager/edgehog-device-runtime pull request #258
Opened 2023-08-04 13:09 UTC by joshuachp

- Update the dependencies where is possible, some are still pinned by the astarte-message-hub
- Fix some warnings in a match state on the ota_handler
- Reorder the systemd module and remove the allow unused
- Check the result returned by systemd notify

2023-08-08 07:42 UTC, harlem88 requested changes

2023-08-08 07:42 UTC, harlem88 commented on CHANGELOG.md
> +## 0.7.2 - Unreleased
```suggestion
## [Unreleased]
```

2023-08-09 09:08 UTC, harlem88 approved these changes

2023-08-09 09:20 UTC, rgallor approved these changes

2023-08-09 12:24 UTC, joshuachp commented on Cargo.toml
> +tonic = "0.8.3"
There is a major version update of tonic, which will conflict with the types in the astarete-message-hub. 

The astarte-message-hub should probably re-export tonic crate (FYI @harlem88), so the same version is accessible from outside.

2023-08-11 08:22 UTC, merged