Add boot_id to SystemStatus
edgehog-device-manager/edgehog-device-runtime pull request #27
Opened 2022-03-11 14:00 UTC by shikoku1

Add boot_id to SystemStatus using `/proc/sys/kernel/random/boot_id`

2022-03-17 15:54 UTC, FrancescoVaiani approved these changes

2022-03-22 09:01 UTC, bettio commented on src/telemetry/system_status.rs
> +        boot_id: std::fs::read_to_string("/proc/sys/kernel/random/boot_id")?
`procfs/src/sys/kernel/random.rs` ~> `pub fn boot_id() -> ProcResult<String>`

2022-03-22 09:01 UTC, bettio commented on src/telemetry/system_status.rs
> +        boot_id: std::fs::read_to_string("/proc/sys/kernel/random/boot_id")?
`procfs/src/sys/kernel/random.rs` ~> `pub fn boot_id() -> ProcResult<String>`

2022-03-22 10:10 UTC, bettio requested changes
Let's use `boot_id()`.

2022-03-23 12:30 UTC, bettio approved these changes

2022-03-23 12:31 UTC, merged