Feature/create volume req
edgehog-device-manager/edgehog-device-runtime pull request #297
Opened 2023-11-02 11:25 UTC by joshuachp

Closes #278

2024-10-21 10:03 UTC, joshuachp commented on edgehog-device-runtime-containers/src/docker/volume.rs
> +        Ok(Some(volume))
Yeh, that's better

2024-10-21 14:20 UTC, harlem88 requested changes

2024-10-21 14:20 UTC, harlem88 commented on edgehog-device-runtime-containers/src/docker/volume.rs
> +                return Ok(None);
You can remove `return`.
```suggestion
                Ok(None)
```

2024-10-21 14:20 UTC, harlem88 commented on edgehog-device-runtime-containers/src/docker/volume.rs
> +            Err(err) => return Err(VolumeError::Inspect(err)),
same
```suggestion
            Err(err) => Err(VolumeError::Inspect(err)),
```

2024-10-21 14:49 UTC, joshuachp commented on edgehog-device-runtime-containers/src/docker/volume.rs
> +                return Ok(None);
Thanks fixed

2024-10-24 13:36 UTC, harlem88 approved these changes

2024-10-24 15:18 UTC, lucaato approved these changes

2024-10-24 15:28 UTC, merged