fix(storage): remove disks with a depth higher than /dev
edgehog-device-manager/edgehog-device-runtime pull request #343
Opened 2024-03-05 12:04 UTC by rgallor

This should temporarily provide a solution to the second point explained in #232

2024-03-06 09:01 UTC, harlem88 requested changes

2024-03-06 09:01 UTC, harlem88 commented on src/telemetry/storage_usage.rs
> +                disk.name().to_str().unwrap().replace("/dev/", ""),
Remove the `unwrap()`

2024-03-06 09:29 UTC, joshuachp requested changes

2024-03-06 09:29 UTC, joshuachp commented on src/telemetry/storage_usage.rs
> +        })
This can be simplified in a `flat_map`

2024-03-06 09:29 UTC, joshuachp commented on src/telemetry/storage_usage.rs
>              },
Prefer collect to fold

2024-03-06 09:29 UTC, joshuachp commented on src/telemetry/storage_usage.rs
> +        .iter()
Can this be a `into_iter()`? To have an owned value

2024-03-06 17:12 UTC, harlem88 approved these changes

2024-03-20 14:29 UTC, joshuachp approved these changes

2024-03-20 16:27 UTC, merged