chore(deps): update the sdk to fix the purge property
edgehog-device-manager/edgehog-device-runtime pull request #369
Opened 2024-05-23 10:19 UTC by rgallor

2024-05-24 10:15 UTC, harlem88 requested changes

2024-05-24 10:15 UTC, harlem88 commented on Cargo.toml
>  sysinfo = "0.26.2"
Bump astarte-message-hub to  `0.5.4`

2024-05-27 12:20 UTC, joshuachp approved these changes

2024-05-27 12:32 UTC, harlem88 approved these changes

2024-05-27 12:33 UTC, merged