Implement io.edgehog.devicemanager.Commands
edgehog-device-manager/edgehog-device-runtime pull request #40
Opened 2022-03-23 15:54 UTC by shikoku1

Implement `io.edgehog.devicemanager.Commands`

The new server owned interface is added with an improved selector for incoming data, removing the nested ifs that were there before

closes #19

2022-03-24 09:44 UTC, harlem88 requested changes

2022-03-24 09:44 UTC, harlem88 commented on src/ota_handler.rs
> +        data: HashMap<String, AstarteType>,
Create another PR regarding `OTA_Handler` changes

2022-04-07 15:15 UTC, harlem88 approved these changes

2022-04-07 15:29 UTC, FrancescoVaiani approved these changes

2022-04-07 15:54 UTC, bettio approved these changes

2022-04-07 15:55 UTC, merged