feat(cellular): add support for `CellularConnectionProperties`
edgehog-device-manager/edgehog-device-runtime pull request #402
Opened 2024-09-30 14:55 UTC by joshuachp

Add support to the `CellularModems` D-Bus service to retrieve the data
for `io.edgehog.devicemanager.CellularConnectionProperties`.

Closes #17

2024-09-30 15:01 UTC, joshuachp commented
I've ported the previous PR. The biggest change is that we connect to the system `dbus` instead of the session, like for the other dbus services.

2024-10-16 15:44 UTC, rgallor requested changes

2024-10-16 15:44 UTC, rgallor commented on cellular-modems-service/README.md
> +Reference project of a service that expose APis to add and retrieve cellular modems data.
typo APIs

2024-10-16 15:44 UTC, rgallor commented on cellular-modems-service/src/main.rs
> +        modem.cloned().unwrap_or_default()
you could simplify with
```suggestion
self.modems.get(&id).cloned().unwrap_or_else(|| {
    debug!("modem {id} not found");
    ModemProperties::default()
})
```

2024-10-16 15:44 UTC, rgallor commented on Cargo.toml
> +members = [ "cellular-modems-service",
i'd rather put it on a new line

2024-10-18 09:15 UTC, merged