refactor(container): improve the services code
edgehog-device-manager/edgehog-device-runtime pull request #435
Opened 2024-11-06 13:28 UTC by joshuachp

- Do not error when sending data to Astarte
- Don't pass closures to the graph but the full node
- Move all the logic to the node to reduce all the function calls

2024-11-13 11:14 UTC, rgallor requested changes

2024-11-13 11:14 UTC, rgallor commented on edgehog-device-runtime-containers/src/service/node.rs
> +            }
You can merge the 2 using `State::Received | State::Stored => {...}`

2024-11-14 10:59 UTC, harlem88 approved these changes

2024-11-14 11:21 UTC, rgallor approved these changes

2024-11-14 14:16 UTC, merged