feature(contaienr): update between two deployments
edgehog-device-manager/edgehog-device-runtime pull request #436
Opened 2024-11-08 11:30 UTC by joshuachp

Add the interface to update from a deployment to another one.

2024-11-13 11:37 UTC, rgallor requested changes

2024-11-13 11:37 UTC, rgallor commented on edgehog-device-runtime-containers/src/service/mod.rs
> +    async fn update_deployment(&mut self, from: Id, to: Id) -> Result<()>
I'd add a brief description about what this function does

2024-11-14 11:03 UTC, harlem88 requested changes

2024-11-14 11:03 UTC, harlem88 commented on edgehog-device-runtime-containers/src/service/mod.rs
> +        debug!("sopping {} containers", to_stop_ids.len());
```suggestion
        debug!("stopping {} containers", to_stop_ids.len());
```

2024-11-15 17:27 UTC, harlem88 approved these changes

2024-11-18 10:52 UTC, lucaato approved these changes

2024-11-18 10:53 UTC, merged