refactor(state): store the resource state
edgehog-device-manager/edgehog-device-runtime pull request #451
Opened 2024-11-19 15:32 UTC by joshuachp

This removes some warnings on restart, when the resources are loaded with state stored.
Now they are loaded with the actual state.

2024-11-19 16:58 UTC, harlem88 requested changes

2024-11-19 16:58 UTC, harlem88 commented on edgehog-device-runtime-containers/src/service/resource.rs
> +            State::Published => "Stored",
Do you want to keep `Stored` as Display?
```suggestion
            State::Published => "Published",
```

2024-11-20 09:43 UTC, rgallor requested changes

2024-11-20 09:43 UTC, rgallor commented on edgehog-device-runtime-containers/src/service/resource.rs
> +    // The resource was is running
remove `was`

2024-11-20 16:12 UTC, merged