chore(changelog): update the changelog
edgehog-device-manager/edgehog-device-runtime pull request #463
Opened 2024-11-28 11:15 UTC by joshuachp

2024-11-29 11:15 UTC, rgallor approved these changes

2025-01-07 11:28 UTC, harlem88 requested changes
- Add little description about container feature to [doc/os_requirements.md](doc/os_requirements.md) and how to enable it as feature.
- Add container feature to [Implemented Features](https://github.com/edgehog-device-manager/edgehog-device-runtime/tree/release-0.9?tab=readme-ov-file#implemented-features) lists.

2025-01-07 11:29 UTC, harlem88 commented on edgehog-device-runtime-containers/CHANGELOG.md
> +## [0.1.0] - Unreleased
We want keep a different version from device-runtime?

2025-01-07 11:31 UTC, harlem88 commented on edgehog-device-runtime-containers/CHANGELOG.md
> +## [0.1.0] - Unreleased
Since currently we release all features below device-runtime single release, I would like keep  a unique version.

2025-01-14 17:39 UTC, harlem88 commented on e2e-test-containers/README.md
> +  Copyright 2023-2024 SECO Mind Srl
```suggestion
  Copyright 2023-2025 SECO Mind Srl
```

2025-01-15 10:40 UTC, harlem88 approved these changes

2025-01-15 13:17 UTC, merged