Deviceinfo support
edgehog-device-manager/edgehog-device-runtime pull request #60
Opened 2022-05-04 13:18 UTC by FrancescoVaiani

- Add System Info DBUS service implementation with part number and serial number from dmi or provided by kernel cmdline.
- Add `io.edgehog.devicemanager.SystemInfo` in the runtime with data fetched from the dbus.

2022-05-05 15:12 UTC, harlem88 requested changes

2022-05-05 15:12 UTC, harlem88 commented on system-info-dbus-service/io.edgehog.SystemInfo.conf
> +    <allow send_destination="org.secomind.SystemInfo"/>
Let's use everywhere: `io.edgehog`

2022-07-20 10:22 UTC, bettio requested changes
Here I have some comments about the logic behind this.

SystemInfo is meant to be the system identification, that is on a higher abstraction level in comparison to the hardware identification. Therefore I'm not sure that using any DMI or hardware identification is the right thing to do here.
The same kind of hardware might have different kind of systems, so the configuration should be taken elsewhere.
I think we might get rid of the DMI and d-bus stuff here, and use env or kernel cmdline as an easy way to inject the system part number and serial number.

2022-07-20 15:39 UTC, bettio commented
kernel documentation says:

> The kernel parses parameters from the kernel command line up to “–”; if it doesn’t recognize a parameter and it doesn’t contain a ‘.’, the parameter gets passed to init: parameters with ‘=’ go into init’s environment, others are passed as command line arguments to init. Everything after “–” is passed as an argument to init.

2022-07-20 15:42 UTC, bettio requested changes

2022-07-20 15:42 UTC, bettio commented on src/telemetry/system_info.rs
> +    let mut seral_number: Option<String> = env::var("SERIAL_NUMBER").ok();
SYSTEM_SERIAL_NUMBER

2022-07-20 15:42 UTC, bettio commented on src/telemetry/system_info.rs
> +    let mut part_number: Option<String> = env::var("PART_NUMBER").ok();
SYSTEM_PART_NUMBER

2022-07-20 15:42 UTC, bettio commented on src/telemetry/system_info.rs
> +        if seral_number.is_none() && param.starts_with("serial_number") {
system_serial_number

2022-07-20 15:42 UTC, bettio commented on src/telemetry/system_info.rs
> +        if part_number.is_none() && param.starts_with("part_number") {
system_part_number

2022-07-20 15:42 UTC, bettio commented on src/telemetry/system_info.rs
> +    let mut seral_number: Option<String> = env::var("SERIAL_NUMBER").ok();
maybe also we should prefix all of the with `EDGHOG_`.

2022-07-20 15:42 UTC, bettio commented on src/telemetry/system_info.rs
> +    for param in cmdline_params.iter() {
Do we really need to handle kernel command line?

2022-07-21 16:11 UTC, harlem88 approved these changes

2022-07-21 16:37 UTC, bettio approved these changes

2022-07-21 16:37 UTC, merged