Remove single file storage
edgehog-device-manager/edgehog-device-runtime pull request #81
Opened 2022-06-20 16:35 UTC by harlem88

Signed-off-by: Antonio Gisondi <antonio.gisondi@secomind.com>

2022-06-30 16:36 UTC, rbino requested changes
Additional note: this would break compatibility for existing devices with credentials saved already saved in the store file, they would have to be manually unregistered. Is this acceptable? @bettio

2022-07-01 10:21 UTC, Annopaolo requested changes
Just a minor comment

2022-07-01 10:21 UTC, Annopaolo commented on src/lib.rs
> +        let credential_secret: String = get_credentials_secret(
Using `credentials_secret` as variable name would be more consistent

2022-07-01 10:21 UTC, Annopaolo commented on src/lib.rs
> +                format!("credential_{}.json", device_id),
See above, s/credential/credentials

2022-07-08 14:08 UTC, Annopaolo approved these changes

2022-07-11 07:36 UTC, rbino approved these changes

2022-07-11 13:27 UTC, bettio approved these changes

2022-07-11 13:27 UTC, merged